#!/bin/sh

notify() {
    notify-send --expire-time=1500 "sxiv" "$1"
}

while read -r file; do
    case "$1" in
        w)
            [ "$(printf "No\nYes" | rofi -dmenu -i -p "Set as wallpaper temporarily?")" = Yes ] &&
                feh --no-fehbg --bg-scale "$file" &&
                notify "$file set as wallpaper"
            exit
            ;;
        W)
            [ "$(printf "No\nYes" | rofi -dmenu -i -p "Set as wallpaper permanently?")" = Yes ] &&
                ln -sf "$(realpath "$file")" "$HOME/.config/wallpaper" &&
                feh --no-fehbg --bg-scale "$file" &&
                notify "$file set as wallpaper"
            exit
            ;;
        d)
            [ "$(printf "No\nYes" | rofi -dmenu -i -p "Delete $(realpath "$file")?")" = Yes ] &&
                rm "$file" &&
                notify "$file deleted" &
            ;;
    esac
done
