#!/bin/sh

# ~/.xinitrc

export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS="@im=fcitx"

export QT_QPA_PLATFORMTHEME=qt5ct

xrdb -merge ~/.config/X11/Xresources
xmodmap ~/.config/X11/Xmodmap

xset s 900 120
xset dpms 0 0 0
xset -dpms

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

eval "$(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)"
export SSH_AUTH_SOCK

picom &
dunst &
fcitx5 &
nm-applet &
# blueman-applet &
# xsettingsd &
feh --no-fehbg --bg-scale "$HOME/.config/wallpaper" &
pgrep -xf 'xcape -e Control_L Escape' || xcape -e 'Control_L=Escape'

scripts=$HOME/.config/i3/scripts
xss-lock -n "$scripts/dim-screen.sh" -- "$scripts/lock.sh" &
"$scripts/xmodmap-on-new-input.sh" &

~/.config/polybar/start.sh &
dropdownterm &
alacritty &

exec i3
