# shellcheck shell=bash

[[ $- != *i* ]] && return

HISTFILE=${XDG_CACHE_HOME:-$HOME/.cache}/bash-history
HISTCONTROL=ignoreboth

if [[ $EUID == 0 ]]; then
    PS1='\[\033[01;31m\][\h\[\033[01;36m\] \W\[\033[01;31m\]]\$\[\033[00m\] '
else
    PS1='\[\033[01;32m\][\u@\h\[\033[01;37m\] \W\[\033[01;32m\]]\$\[\033[00m\] '
fi

alias ls='eza'
alias rm='rm -I'
alias cp='cp -i'
alias mv='mv -i'
alias grep='grep --color=auto'

complete -cf sudo

shopt -s histappend
