. ~/.dotfiles/zsh/basic.zsh
. ~/.dotfiles/zsh/env.zsh
. ~/.dotfiles/zsh/aliases.zsh
. ~/.dotfiles/zsh/functions.zsh
. ~/.dotfiles/zsh/completion.zsh

for f in ~/.dotfiles/zsh/apps/*; do
	. $f
done

[[ -f ~/.dotfiles/local/zshrc ]] && \. ~/.dotfiles/local/zshrc || true

unset f plugins
