. ~/.dotfiles/zsh/basic.zsh
to_source=($(find ~/.dotfiles/zsh -maxdepth 1 -type f | grep -v basic.zsh))
for f in $to_source; do
	. $f
done
unset to_source

for f in ~/.dotfiles/zsh/apps/*; do
	. $f
done

[[ -f ~/.dotfiles/local/zshrc ]] && \. ~/.dotfiles/local/zshrc || true
